# Generated by Django 3.2.3 on 2021-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_alter_message_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=166),
        ),
    ]
